AllCops:
  Exclude:
    - 'vendor/gems/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'bin/*'

BlockLength:
  Exclude:
    - 'config/routes.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

MethodLength:
  Enabled: true
  Max: 25

Style/BlockComments:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Metrics/AbcSize:
  Max: 20
