AllCops:
  Exclude:
    - vendor/**/*
    - db/migrate/*
    - db/schema.rb
    - bin/*

BlockLength:
  Exclude:
    - config/routes.rb
    - spec/**/*

LineLength:
  Enabled: false

Documentation:
  Enabled: false

OrderedGems:
  Enabled: false

BlockComments:
  Enabled: false
